<a href="https://colab.research.google.com/github/anumit-web/TensorFlow-tutorial-4/blob/main/TensorFlow_test_4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow Tutorial

https://www.geeksforgeeks.org/tensorflow/

# Extracting tensors

grab specific elements or chunks of your data

Unlike slicing, you don’t need them to be neatly lined up

In [14]:
import tensorflow as tf
t1 = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])
t1
favorites = tf.gather(t1, indices=[0, 3, 6])
print(favorites) # Output: [0 3 6]


tf.Tensor([0 3 6], shape=(3,), dtype=int32)


In [15]:
t2 = tf.constant([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8]])
t2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [16]:
Indices = tf.constant([1, 0])
r = tf.gather(t2, indices=Indices, axis=0)
print('Along Row\n',r)

c = tf.gather(t2, indices=Indices, axis=1)
print('\nAlong Columns\n',c)

Along Row
 tf.Tensor(
[[3 4 5]
 [0 1 2]], shape=(2, 3), dtype=int32)

Along Columns
 tf.Tensor(
[[1 0]
 [4 3]
 [7 6]], shape=(3, 2), dtype=int32)


In [17]:
t3 = tf.constant([[[1, 3, 5, 7],
                   [9, 11, 13, 15]],
                  [[17, 19, 21, 23],
                   [25, 27, 29, 31]]])
t3

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 1,  3,  5,  7],
        [ 9, 11, 13, 15]],

       [[17, 19, 21, 23],
        [25, 27, 29, 31]]], dtype=int32)>

In [18]:
Indices = [[0, 0, 0], [1, 1, 1], [1, 0, 3]]
special_picks = tf.gather_nd(t3, indices=Indices, batch_dims=0)
print(special_picks)

tf.Tensor([ 1 27 23], shape=(3,), dtype=int32)


## 3. Inserting tensors

In [19]:
import tensorflow as tf
t4 = tf.zeros_like(tf.constant([0, 0, 0, 0, 0, 0, 0, 0]))
t4

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>

In [20]:
Index = [[1], [3], [6]]
values = [10, 20, 30]
t4 = tf.scatter_nd(indices=Index,
                   updates=values,
                   shape=[8])
print(t4)  # Output: [0 10 0 20 0 0 30 0]

tf.Tensor([ 0 10  0 20  0  0 30  0], shape=(8,), dtype=int32)


In [21]:
t5 = tf.zeros(shape=(4, 5))
t5

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [22]:
Index = [[0, 0],
         [1, 1],
         [2, 2]]
values = [100, 200, 300]
t5 = tf.scatter_nd(indices=Index,
                   updates=values,
                   shape=t5.shape)
print(t5)  # Output: [[100 0 0 0 0], [0 200 0 0 0], [0 0 300 0 0], [0 0 0 0 0]]

tf.Tensor(
[[100   0   0   0   0]
 [  0 200   0   0   0]
 [  0   0 300   0   0]
 [  0   0   0   0   0]], shape=(4, 5), dtype=int32)
