<a href="https://colab.research.google.com/github/anumit-web/TensorFlow-tutorial-4/blob/main/TensorFlow_test_4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow Tutorial

https://www.geeksforgeeks.org/tensorflow/

# Extracting tensors

grab specific elements or chunks of your data

Unlike slicing, you don’t need them to be neatly lined up

In [2]:
import tensorflow as tf
t1 = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])
t1
favorites = tf.gather(t1, indices=[0, 3, 6])
print(favorites) # Output: [0 3 6]


tf.Tensor([0 3 6], shape=(3,), dtype=int32)


In [3]:
t2 = tf.constant([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8]])
t2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [4]:
Indices = tf.constant([1, 0])
r = tf.gather(t2, indices=Indices, axis=0)
print('Along Row\n',r)

c = tf.gather(t2, indices=Indices, axis=1)
print('\nAlong Columns\n',c)

Along Row
 tf.Tensor(
[[3 4 5]
 [0 1 2]], shape=(2, 3), dtype=int32)

Along Columns
 tf.Tensor(
[[1 0]
 [4 3]
 [7 6]], shape=(3, 2), dtype=int32)
