<a href="https://colab.research.google.com/github/anumit-web/TensorFlow-tutorial-4/blob/main/TensorFlow_test_4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow Tutorial

https://www.geeksforgeeks.org/tensorflow/

tensor means arrays.
arrays can be 1d, 2d, 3d, 4d etc

working with 1d array

In [33]:
import tensorflow as tf
t1 = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])   # create 1d array
t1


<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int32)>

In [34]:
print(t1)

tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)


In [35]:
s1 = tf.slice(t1, begin=[1], size=[3])
print(s1) # Output: [1 2 3]

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [36]:
s1 = t1[1:4] # Same output as above
print(s1)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


working with 2d array

In [37]:
t2 = tf.constant([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8]])
t2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [46]:
# Get the first row
first_row = tf.slice(t2, [0, 0], [1, tf.shape(t2)[1]])  # 1,3
print('First Row:\n', first_row)
print("hello", tf.shape(t2)[1])

# Get the second column
second_column = tf.slice(t2, [0, 1], [tf.shape(t2)[0], 1]). # 3,1
print('\nSecond Column:\n', second_column)

# Get the second and third columns
second_third_columns = tf.slice(t2, [0, 1], [tf.shape(t2)[0], 2]) # 3,2
print('\nSecond & Third Columns:\n', second_third_columns)

First Row:
 tf.Tensor([[0 1 2]], shape=(1, 3), dtype=int32)
hello tf.Tensor(3, shape=(), dtype=int32)

Second Column:
 tf.Tensor(
[[1]
 [4]
 [7]], shape=(3, 1), dtype=int32)

Second & Third Columns:
 tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)


In [48]:
# Get the first row
print('First Row:\n', t2[0])

# Get the second column
print('\nSecond columns:\n', t2[:, 1]) # all rows, one column only

# Get the second and third columns
print('\nSecond & Third columns:\n', t2[:, 1:3]) # all rows, columns start from 1

First Row:
 tf.Tensor([0 1 2], shape=(3,), dtype=int32)

Second columns:
 tf.Tensor([1 4 7], shape=(3,), dtype=int32)

Second & Third columns:
 tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)
