<a href="https://colab.research.google.com/github/anumit-web/TensorFlow-tutorial-4/blob/main/TensorFlow_test_4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow Tutorial

https://www.geeksforgeeks.org/tensorflow/

tensor means arrays.
arrays can be 1d, 2d, 3d, 4d etc

working with 1d array

In [7]:
import tensorflow as tf
t1 = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])   # create 1d array
t1


<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int32)>

In [8]:
print(t1)

tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)


In [9]:
s1 = tf.slice(t1, begin=[1], size=[3])
print(s1) # Output: [1 2 3]

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [12]:
s1 = t1[1:4] # Same output as above
print(s1)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


working with 2d array